
-- created a user/schema named bank_reviews
create user bank_reviews identified by your_password;


CREATE TABLE banks (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    app_name VARCHAR2(150) -- e.g., "Commercial Bank of Ethiopia Mobile"
);

CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    review_text CLOB NOT NULL,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    review_date DATE NOT NULL,
    sentiment_label VARCHAR2(10),  -- 'positive', 'negative', 'neutral'
    sentiment_score FLOAT,
    theme VARCHAR2(100),  -- e.g., 'Login Issues', 'App Performance'
    bank_id NUMBER,
    source VARCHAR2(50), -- e.g., 'Google Play'
    FOREIGN KEY (bank_id) REFERENCES banks(id)
);
